### ISSUE TITLE
Error in Xcode

### ISSUE THREAD

**Issue by fabiofolgori** [a31859/ImageDetectionDemoApp#1]
Hi,
i've this error in XCode when I run the app on iOS
`0x18e18fd74 <+8>:  b.lo   0x18e18fd8c               ; <+32>`

**Comment by a31859** [comment]
Hello, can you put the full error log?

**Comment by AlbertoFCasarrubias** [comment]
I got this 
Ordered comparison between pointer and zero ('NSNumber *' and 'int')

**Comment by a31859** [comment]
@yaotzin68 This is most likely an error in the plugin. Can you tell me which version of iOS you used?

**Comment by Antoine38660** [comment]
I got the same error with iOS11.

I fixed the issue by adding `(void *)` before the 0 in the ImageDetectionPlugin.mm (line 129 [here](https://github.com/a31859/ImageDetectionDemoApp/blob/master/plugins/com.cloudoki.imagedetectionplugin/src/ios/ImageDetectionPlugin.mm#L129)) : 
`if (argVal != nil && argVal > (void *) 0) {`

**Comment by Antoine38660** [comment]
You'll probably get another issue about "Privacy - Camera Usage Description". To fix this one, simply add an entry in the Info.plist file with key: "Privacy - Camera Usage Description" and value: "Anything -> a string".


Cheers 😄

**Comment by a31859** [comment]
@Antoine38660 Thanks for the fix 😄
