### ISSUE TITLE
opencv cordova plugin issue

### ISSUE THREAD

**Issue by sunilvchalla** [a31859/ImageDetectionDemoApp#2]
camera  not intailizing  it always struck with spalsh screen device ready when open app. In android 4.5 vesrion camera flash for just 2 sec then go to device ready splash screen

please help me

**Comment by a31859** [comment]
Can you try pointing the camera to one of the targets to see if any of the alert shows? If it show then the issue is that the cordova webview that is on top of the camera is not transparent resulting in blocking the camera view.

**Comment by sunilvchalla** [comment]
its work fine but it did'nt recognise logo image ,any way to  recognise logo image.my logo image is black and white is ther any pblm in black & white image detection

**Comment by a31859** [comment]
The detection is done using feature matching, as described [here](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_feature_homography/py_feature_homography.html). If the image does not have a good enough feature set it will be difficult to have a successful match.

**Comment by sunilvchalla** [comment]
any way to  change  ionic modal pop insted of alert in isdetction success function .ionic popup modal not working because transparency  issue  in the style. camera cannot open in ionic controller function. please help me

**Comment by sunilvchalla** [comment]
how to install and import this plugin in ionic2.can you give the sample code in ionic2

**Comment by a31859** [comment]
To add the plugin to ionic you follow these steps:
- clone the plugin repo:
`git clone https://github.com/Cloudoki/ImageDetectionCordovaPlugin.git`
- go into your project root folder:
`cd <your-project-root>`
- add the plugin to the project:
`ionic cordova plugin add /path/to/the/plugin/plugin.folder.here/`
or
`ionic plugin add /path/to/the/plugin/plugin.folder.here/`

**Note:**
I have not tested the plugin in ionic 2 so some issues might occur.

**Comment by sunilvchalla** [comment]
ok its work in ionic2 .some time it detect wrong image

**Comment by sunilvchalla** [comment]
is it any way set pattern of images downloaded to my device folder from  server . cannot set images from device folder lik e documentsdirctor,data directory in the patterns image not set from this folder
