### ISSUE TITLE
IOS Build issue

### ISSUE THREAD

**Issue by fariskas** [a31859/ImageDetectionDemoApp#4]
just downloaded the app and i'm trying to build the app on XCode for ios 11.0 and i faced the following error:

```
/Users/faris/Desktop/phonegap/ImageDetectionDemoApp/platforms/ios/HelloCordova/Plugins/com.cloudoki.imagedetectionplugin/ImageDetectionPlugin/ImageDetectionPlugin.mm:129:37: error: ordered comparison between pointer and zero ('NSNumber *' and 'int')
        if (argVal != nil && argVal > 0) {
                             ~~~~~~ ^ ~
1 warning and 1 error generated.
```

any idea how i can fix this?

**Comment by a31859** [comment]
Hey @fariskas that was already fixed in the plugin repo but the demo was not up to date with the changes that's the reason the error was still showing here. 
I've updated it so it should be working now.
