### ISSUE TITLE
How to open camera on screen

### ISSUE THREAD

**Issue by greceanii** [a31859/ImageDetectionDemoApp#6]
plugin detect image but not open camera on screen

**Comment by a31859** [comment]
Hi @greceanii, the camera layer is added below the webview, so the webview background needs to be transparent in order for the camera to show. In case it already is, then it could be related to this [issue](https://github.com/Cloudoki/ImageDetectionCordovaPlugin/issues/20).

**Comment by greceanii** [comment]
@a31859 thanks, i solve

**Comment by ganesh8184** [comment]
How did you solve that
