### ISSUE TITLE
It seems to be not compatible with Android@7.0.0 on Cordova

### ISSUE THREAD

**Issue by mcolentava** [a31859/ImageDetectionDemoApp#7]
Hi there, I am trying to use it for Android default platform. And it seems to be incompatible with the latest version which is 7.0+

**Comment by a31859** [comment]
Hello @mcolentava, currently I don't have much time available to look into this but as soon as able I'll try to test it in a Android 7 device and see what can be done, probably this weekend.

**Comment by a31859** [comment]
Hello @mcolentava, sorry for the long wait... I've updated the plugin here: https://github.com/Cloudoki/ImageDetectionCordovaPlugin/tree/cordova%407.0.0 
This should work with android@7.0.0, try to use this updated version of the plugin and let me know if it works.
