### ISSUE TITLE
Not able to run or import the package in ionic 3

### ISSUE THREAD

**Issue by saryuvc** [a31859/ImageDetectionDemoApp#8]
Hello,
I want app to detect the object form camera and automatically capture the image.is this plugin provide this functionality?
yes then how to import this plugin to my component

**Comment by a31859** [comment]
Hello @saryuvc, there's code in the plugin used for debugging purposes that saves images but the functionality you want is not provided this would need to be added into the plugin.

**Comment by saryuvc** [comment]
Thank you for reply
